version: 2.1
parameters:
    repo:
        type: string
        default: "rsksmart/rskj.git"
    version:
        type: string
        default: "3.0.0-SNAPSHOT"
    branch:
        type: string
        default: "master"
    slack_channel:
        type: string
        default: "integration-tests"
orbs:
  slack: circleci/slack@4.1
jobs:
  build:
    working_directory: ~/smart-contracts
    # The primary container is an instance of the first image listed. The job's commands run in this container.
    docker:
      - image: circleci/openjdk:8-jdk

    steps:
      - checkout
      - run:
          name: Avoid hosts unknown for github
          command: mkdir -p ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
      - run:
          name: Clone and Build RSKj
          command: |
                    GIT_SSH_COMMAND='ssh -i ~/.ssh/id_rsa_fingerprint'
                    git clone -b << pipeline.parameters.branch >> git@github.com:<< pipeline.parameters.repo >> ~/rsksmart/rskj
                    cd ~/rsksmart/rskj/
                    ./configure.sh
                    ./gradlew clean build -x test
      - run:
          name: Prepare npm
          command: |
                    curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
                    sudo apt update
                    sudo apt-get install -y nodejs
                    sudo apt install build-essential
      - run:
          name: Prepare Truffle
          command: |
                    sudo npm install -g truffle@5.2.4
                    cd ~/smart-contracts/
                    npm install 
      - run:
          name: Start RskJ & Run Truffle Tests
          command: |
                    java -cp ~/rsksmart/rskj/rskj-core/build/libs/rskj-core-<< pipeline.parameters.version >>-all.jar co.rsk.Start --regtest nohup &               
                    until nc -z 127.0.0.1 4444
                    do
                      echo "Waiting for RskJ..."
                      sleep 1
                    done
                    ls ~/smart-contracts/         
                    npm test
      - slack/notify:
          channel: << pipeline.parameters.slack_channel >>
          custom: |
            {
                "blocks": [
                    {
                        "type": "header",
                        "text": {
                            "type": "plain_text",
                            "text": "RskJ Truffle Tests Passed :white_check_mark:",
                            "emoji": true
                        }
                    },
                    {
                        "type": "section",
                        "fields": [
                            {
                                "type": "mrkdwn",
                                "text": "*Tested Repository*: << pipeline.parameters.repo >>"
                            },
                            {
                                "type": "mrkdwn",
                                "text": "*Tested Branch*: << pipeline.parameters.branch >>"
                            },
                            {
                                "type": "mrkdwn",
                                "text": "*Tested Version*: << pipeline.parameters.version >>"
                            }
                        ]
                    },
                    {
                        "type": "actions",
                        "elements": [
                            {
                                "type": "button",
                                "text": {
                                    "type": "plain_text",
                                    "text": "View Job"
                                },
                                "url": "${CIRCLE_BUILD_URL}"
                            }
                        ]
                    }
                ]
                }
          event: pass
      - slack/notify:
          channel: << pipeline.parameters.slack_channel >>
          custom: |
            {
                "blocks": [
                    {
                        "type": "header",
                        "text": {
                            "type": "plain_text",
                            "text": "RskJ Truffle Tests Failed :red_circle:",
                            "emoji": true
                        }
                    },
                    {
                        "type": "section",
                        "fields": [
                            {
                                "type": "mrkdwn",
                                "text": "*Tested Repository*: << pipeline.parameters.repo >>"
                            },
                            {
                                "type": "mrkdwn",
                                "text": "*Tested Branch*: << pipeline.parameters.branch >>"
                            },
                            {
                                "type": "mrkdwn",
                                "text": "*Tested Version*: << pipeline.parameters.version >>"
                            }
                        ]
                    },
                    {
                        "type": "actions",
                        "elements": [
                            {
                                "type": "button",
                                "text": {
                                    "type": "plain_text",
                                    "text": "View Job"
                                },
                                "url": "${CIRCLE_BUILD_URL}"
                            }
                        ]
                    }
                ]
                }
          event: fail
      - store_artifacts:
          path: ~/smart-contracts/logs
          destination: ~/tmp/logs
workflows:
    commit:
        jobs:
            - build
    daily:
        triggers:
            - schedule:
                cron: "15 01 * * *"
                filters:
                    branches:
                        only:
                            - master
        jobs:
            - build
